name: analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: --globals vim -- nvim

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - name: treefmt check
        run: |
          nix flake check
